import numpy as np


def rtp(pnl, best_pnl, worst_pnl, one_sided):
    """
    Compute the Relative Trading Performance (RTP).

    Parameters
    ----------
    pnl : array-like
        Realized PnL values.
    best_pnl : array-like
        Best-case PnL trajectory.
    worst_pnl : array-like
        Worst-case PnL trajectory.
    one_sided : bool
        If True, scales RTP between worst and best PnL.
        If False, scales PnL by the best PnL only.

    Returns
    -------
    float
        Relative trading performance.
    """
    if one_sided:
        return (np.sum(pnl) - np.sum(worst_pnl)) / (
            np.sum(best_pnl) - np.sum(worst_pnl)
        )
    else:
        return np.sum(pnl) / np.sum(best_pnl)


def hhi(pnl):
    """
    Compute the Herfindahl–Hirschman Index (HHI) of profit concentration.

    Parameters
    ----------
    pnl : array-like
        Profit or PnL series.

    Returns
    -------
    float
        HHI concentration measure (0 to 1).
    """
    return np.sum((pnl / np.sum(pnl)) ** 2)


def gini(pnl):
    """
    Compute the Gini coefficient of profit concentration using pairwise differences.

    Parameters
    ----------
    pnl : array-like
        Profit or return series.

    Returns
    -------
    float
        Gini coefficient, between 0 and 1.
    """
    pnl = pnl[pnl > 0]  # only positive profits
    n = pnl.size
    if n == 0:
        return 0.0
    mean_x = np.mean(pnl)
    if mean_x == 0:
        return 0.0
    diff_sum = np.abs(pnl[:, None] - pnl).sum()  # pairwise absolute differences
    return diff_sum / (2 * n**2 * mean_x)


def topk_contribution(pnl, k=2016):
    """
    Compute the percentage contribution of the top-k profitable points.

    Parameters
    ----------
    pnl : array-like
        Profit or PnL series.
    k : int, optional
        Number of top profit observations to consider.
        Default 2016 corresponds to 21 days * 96 quarter hours of paid leave common in EU.

    Returns
    -------
    float
        Fraction of total profit generated by the top-k positive PnL values.
    """
    positives = pnl[pnl > 0]
    if positives.size == 0:
        return 0.0
    total_profit = positives.sum()
    topk_sum = np.sort(positives)[-k:].sum() if positives.size >= k else positives.sum()

    return topk_sum / total_profit


def profit(pnl):
    """
    Compute total profit.
    """
    return np.sum(pnl)


def mdd(pnl):
    """
    Compute the maximum drawdown.
    """
    equity = np.cumsum(pnl)
    peak = np.maximum.accumulate(equity)
    drawdown = peak - equity
    return np.max(drawdown)


def avg_dd(pnl):
    """
    Compute average drawdown.
    """
    equity = np.cumsum(pnl)
    peak = np.maximum.accumulate(equity)
    drawdown = peak - equity
    return np.mean(drawdown)


def downside_std(pnl, one_sided):
    """
    Compute downside standard deviation.
    """
    if one_sided:
        mu = np.mean(pnl)
        diff = pnl - mu
        downside_sq = np.where(diff < 0, diff**2, 0.0)
    else:
        downside_sq = np.where(pnl < 0, pnl**2, 0.0)

    return np.sqrt(downside_sq.mean())


def win_rate(pnl):
    """
    Compute win rate (fraction of positive-PnL observations).
    """
    return len(pnl[pnl > 0]) / len(pnl)
